import { useEffect, useMemo, useState } from 'react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import Modal from '../components/Modal';
import { api } from '../lib/api';
import { money } from '../lib/utils';
import { basePrice, discountedTotals, lineProfitTotal, lineTotal, profitPrice } from '../lib/pricing';
import { useToast } from '../components/ToastProvider';

const startOfDay=(d)=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const endOfDay=(d)=>new Date(d.getFullYear(),d.getMonth(),d.getDate(),23,59,59,999);
const startOfWeek=(d)=>{const x=startOfDay(d);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x;};
const endOfWeek=(d)=>{const x=startOfWeek(d);x.setDate(x.getDate()+6);x.setHours(23,59,59,999);return x;};
const toInput=(d)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const monthNames=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function rangeFor(filter, custom){const n=new Date(); if(filter==='day') return [startOfDay(n),endOfDay(n)]; if(filter==='week') return [startOfWeek(n),endOfWeek(n)]; if(filter==='month') return [new Date(n.getFullYear(),n.getMonth(),1),new Date(n.getFullYear(),n.getMonth()+1,0,23,59,59,999)]; if(filter==='year') return [new Date(n.getFullYear(),0,1),new Date(n.getFullYear(),11,31,23,59,59,999)]; const s=custom?.from?new Date(custom.from+'T00:00:00'):startOfDay(n); const e=custom?.to?new Date(custom.to+'T23:59:59.999'):endOfDay(n); return [s,e];}
function inRange(dateValue,filter,custom){const d=new Date(dateValue),[s,e]=rangeFor(filter,custom);return d>=s&&d<=e;}
function chartSkeleton(filter, custom){const now=new Date(); if(filter==='day'){return Array.from({length:24},(_,h)=>({key:String(h),label:h===0?'12 AM':h===12?'12 PM':h<12?`${h} AM`:`${h-12} PM`,amount:0,events:[]}));} if(filter==='week'){const s=startOfWeek(now);return Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return {key:toInput(d),label:d.toLocaleDateString('en-GB',{weekday:'short'}),amount:0,events:[]};});} if(filter==='month'){const days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return Array.from({length:days},(_,i)=>({key:String(i+1),label:String(i+1),amount:0,events:[]}));} if(filter==='year'){return monthNames.map((m,i)=>({key:String(i),label:m,amount:0,events:[]}));} const [s,e]=rangeFor(filter,custom); const days=Math.max(1,Math.ceil((endOfDay(e)-startOfDay(s))/864e5)+1); return Array.from({length:days},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return {key:toInput(d),label:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'}),amount:0,events:[]};});}
function chartBucket(dateValue,filter){const d=new Date(dateValue); if(filter==='day')return String(d.getHours()); if(filter==='week'||filter==='custom')return toInput(d); if(filter==='month')return String(d.getDate()); if(filter==='year')return String(d.getMonth()); return toInput(d);}
function FilterControls({filter,setFilter,custom,setCustom,allowYear=false}){return <div className="miniFilters"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option>{allowYear&&<option value="year">Year</option>}<option value="custom">Custom date range</option></select>{filter==='custom'&&<><input type="date" value={custom.from} onChange={e=>setCustom({...custom,from:e.target.value})}/><input type="date" value={custom.to} onChange={e=>setCustom({...custom,to:e.target.value})}/></>}</div>}

export default function Finance({ refreshKey, refresh }) {
  const toast = useToast();
  const [orders,setOrders]=useState([]),[items,setItems]=useState([]),[payments,setPayments]=useState([]),[supplierOrders,setSupplierOrders]=useState([]),[expenses,setExpenses]=useState([]),[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[metricFilter,setMetricFilter]=useState('day'),[expenseFilter,setExpenseFilter]=useState('day'),[chartFilter,setChartFilter]=useState('day'),[modal,setModal]=useState(false);
  const today=toInput(new Date());
  const [metricCustom,setMetricCustom]=useState({from:today,to:today}),[expenseCustom,setExpenseCustom]=useState({from:today,to:today}),[chartCustom,setChartCustom]=useState({from:today,to:today});
  const load=()=>Promise.all([api.listPosOrders(),api.listPosOrderItems(),api.listPosPayments(),api.listSupplierOrders(),api.listExpenses(),api.listCategories(),api.listProducts()]).then(([o,i,p,so,e,c,pr])=>{setOrders(o);setItems(i);setPayments(p);setSupplierOrders(so);setExpenses(e);setCategories(c);setProducts(pr);});
  useEffect(()=>{load();},[refreshKey]);

  const paymentsByOrder=useMemo(()=>{const map={}; payments.forEach(p=>{(map[p.pos_order_id] ||= []).push(p);}); return map;},[payments]);
  const orderProfit=(o)=>{const stored=Number(o.total_profit); if(o.total_profit!==undefined&&o.total_profit!==null&&Number.isFinite(stored))return stored; const orderItems=items.filter(i=>i.pos_order_id===o.id); const profitSubtotal=orderItems.reduce((s,i)=>{const product=products.find(p=>p.id===i.product_id); return s+lineProfitTotal(i.profit_price ?? profitPrice(product), i.quantity);},0); return discountedTotals(Number(o.subtotal||0), profitSubtotal, o.discount_type, o.discount_value).profit;};
  const paymentEvents=useMemo(()=>{const events=[]; orders.forEach(o=>{const orderPayments=paymentsByOrder[o.id]||[]; if(orderPayments.length){orderPayments.forEach(p=>events.push({order:o, amount:Number(p.amount||0), date:p.payment_date||p.created_at, label:p.note||'Payment'}));} else if(o.paid){events.push({order:o, amount:Number(o.total_price||0), date:o.paid_at||o.created_at, label:'Legacy full payment'});}}); return events;},[orders,paymentsByOrder]);

  const metricPayments=paymentEvents.filter(e=>inRange(e.date,metricFilter,metricCustom));
  const revenue=metricPayments.reduce((s,e)=>s+Number(e.amount||0),0);
  const totalProfit=metricPayments.reduce((s,e)=>{const total=Number(e.order.total_price||0); return s+(total ? orderProfit(e.order)*(Number(e.amount||0)/total) : 0);},0);
  const totalStockPrice=products.reduce((s,p)=>s+lineTotal(basePrice(p), p.quantity),0);
  const metricSupplierExpenses=supplierOrders.filter(o=>o.status==='arrived'&&inRange(o.created_at,metricFilter,metricCustom)).reduce((s,o)=>s+Number(o.total_price||0),0);
  const metricManualExpenses=expenses.filter(e=>inRange(e.created_at,metricFilter,metricCustom)&&!(e.is_supplier&&e.payment_status!=='paid')).reduce((s,e)=>s+Number(e.price||0),0);
  const totalExpenses=metricSupplierExpenses+metricManualExpenses;
  const paidAmountForOrder=(orderId)=>Number((paymentsByOrder[orderId]||[]).reduce((s,p)=>s+Number(p.amount||0),0));
const totalNotPaid = orders
  .filter(
    o =>
      inRange(o.created_at, metricFilter, metricCustom) &&
      o.payment_status === 'Not Paid'
  )
  .reduce((s, o) => s + Math.max(0, Number(o.total_price || 0) - paidAmountForOrder(o.id)), 0);
  const reportTotal=revenue-totalExpenses+totalStockPrice+totalNotPaid;
  const phoneRevenue=(categoryName)=>{const cat=categories.find(c=>c.name.toLowerCase()===categoryName.toLowerCase());const productIds=products.filter(p=>p.category_id===cat?.id).map(p=>p.id);return items.filter(i=>productIds.includes(i.product_id)).reduce((s,i)=>{const order=orders.find(o=>o.id===i.pos_order_id); if(!order)return s; const paidForOrder=metricPayments.filter(e=>e.order.id===order.id).reduce((x,e)=>x+Number(e.amount||0),0); const ratio=Number(order.total_price||0)?paidForOrder/Number(order.total_price||0):0; return s+Number(i.total_price||0)*ratio;},0)};
  const expenseSupplierRows=supplierOrders.filter(o=>o.status==='arrived'&&inRange(o.created_at,expenseFilter,expenseCustom));
  const expenseManualRows=expenses.filter(e=>inRange(e.created_at,expenseFilter,expenseCustom));
  const chart=useMemo(()=>{const rows=chartSkeleton(chartFilter,chartCustom);paymentEvents.filter(e=>inRange(e.date,chartFilter,chartCustom)).forEach(e=>{const key=chartBucket(e.date,chartFilter);const row=rows.find(r=>r.key===key); if(row){row.amount+=Number(e.amount||0); row.events.push(`${e.order.order_code||'POS order'} • ${new Date(e.date).toLocaleString('en-GB')} • ${money(e.amount)}`);}}); return rows;},[paymentEvents,chartFilter,chartCustom]);
  const saveExpense=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api.createExpense({description:f.get('description'),price:Number(f.get('price'))});setModal(false);load();refresh();toast('Expense added successfully');};
  return <div><div className="pageHeader"><div><h1>Financial Dashboard</h1><p>Revenue and profit are based on actual POS payment dates, including partial payments.</p></div><button className="primary" onClick={()=>setModal(true)}>Add Expense</button></div><div className="dashboardFilter"><div><b>Revenue & Profit Filter</b><p>Total revenue, total profit, net profit, used phones, and new phones use this shared filter.</p></div><FilterControls filter={metricFilter} setFilter={setMetricFilter} custom={metricCustom} setCustom={setMetricCustom}/></div><div className="metrics"><div><span>Total revenue</span><b>{money(revenue)}</b></div><div><span>Total Profit</span><b>{money(totalProfit)}</b></div><div><span>Total Stock Price</span><b>{money(totalStockPrice)}</b></div><div><span>Expenses</span><b>{money(totalExpenses)}</b></div><div><span>Total Not Paid</span><b>{money(totalNotPaid)}</b></div><div><span>Report</span><b>{money(reportTotal)}</b></div></div><div className="panel"><div className="panelHeader"><div><h2>Financial Line Chart</h2><p>POS payments are plotted by their actual payment date, including partial payments.</p></div><FilterControls filter={chartFilter} setFilter={setChartFilter} custom={chartCustom} setCustom={setChartCustom} allowYear/></div><ResponsiveContainer width="100%" height={330}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={(v)=>`$${v}`}/><Tooltip formatter={(v,_,p)=>[money(v),p.payload.events?.join('\n')||'No POS payments']} labelFormatter={(label)=>`Period: ${label}`}/><Line type="monotone" dataKey="amount" stroke="var(--green)" strokeWidth={3} dot={{ r: 4 }} activeDot={{ r: 7 }}/></LineChart></ResponsiveContainer></div><div className="dashboardFilter"><div><b>Expenses Table Filter</b><p>Filters supplier order expenses and manual expenses separately from dashboard cards.</p></div><FilterControls filter={expenseFilter} setFilter={setExpenseFilter} custom={expenseCustom} setCustom={setExpenseCustom}/></div><div className="tableWrap"><table><thead><tr><th>Type</th><th>ID</th><th>Description / Supplier</th><th>Price</th></tr></thead><tbody>{expenseSupplierRows.map(o=><tr key={o.id}><td>Supplier order</td><td>{o.order_code}</td><td>{o.supplier_name}</td><td>{money(o.total_price)}</td></tr>)}{expenseManualRows.map(e=><tr key={e.id}><td>Manual expense</td><td>{e.expense_code}</td><td>{e.description}</td><td>{money(e.price)}</td></tr>)}</tbody></table></div>{modal&&<Modal title="Add Expense" onClose={()=>setModal(false)}><form className="form" onSubmit={saveExpense}><label>Description<input name="description" required placeholder="Example: Rent, delivery, utilities"/></label><label>Price<input name="price" required type="number" step="0.01" placeholder="0.00"/></label><button className="primary">Save Expense</button></form></Modal>}</div>;
}
