import { useEffect, useMemo, useState } from 'react';
import Modal from '../components/Modal';
import { api } from '../lib/api';
import { money } from '../lib/utils';
import { useToast } from '../components/ToastProvider';

export default function Stock({ refreshKey, refresh }) {
  const toast = useToast();
  const [categories,setCategories]=useState([]),[products,setProducts]=useState([]),[active,setActive]=useState(''),[modal,setModal]=useState(null),[edit,setEdit]=useState(null),[categorySearch,setCategorySearch]=useState('');
  const load=()=>Promise.all([api.listCategories(),api.listProducts()]).then(([c,p])=>{setCategories(c);setProducts(p);setActive(a=>a||c[0]?.id||'');});
  useEffect(()=>{load();},[refreshKey]);
  const saveCategory=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const created=await api.createCategory({name:f.get('name'),description:f.get('description')});setActive(created.id);setModal(null);load();refresh();toast('Category created successfully');};
  const saveProduct=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const row={category_id:active,name:f.get('name'),description:f.get('description'),barcode:f.get('barcode'),price:Number(f.get('price')),quantity:Number(f.get('quantity'))}; edit?await api.updateProduct(edit.id,Object.fromEntries(Object.entries(row).filter(([,v])=>v!==''&&!Number.isNaN(v)))):await api.createProduct(row);setEdit(null);setModal(null);load();refresh();toast(edit?'Product updated successfully':'Product added to stock');};
  const filteredCategories = useMemo(()=>categories.filter(c=>`${c.name} ${c.description||''}`.toLowerCase().includes(categorySearch.toLowerCase())),[categories,categorySearch]);
  const rows=products.filter(p=>p.category_id===active);
  const activeCategory = categories.find(c=>c.id===active);
  return <div><div className="pageHeader"><div><h1>Stock Management</h1><p>Create categories and manage product stock.</p></div><div><button className="secondary" onClick={()=>setModal('category')}>Create Category</button><button className="primary" onClick={()=>{setEdit(null);setModal('product');}}>Add Product</button></div></div><div className="stockLayout"><aside className="categoryPanel"><div className="categoryPanelHeader"><h2>Product Types</h2><span>{categories.length} categories</span></div><input className="categorySearch" value={categorySearch} onChange={e=>setCategorySearch(e.target.value)} placeholder="Search categories..."/><div className="categoryList">{filteredCategories.map(c=><button className={active===c.id?'active':''} onClick={()=>setActive(c.id)} key={c.id}><b>{c.name}</b><small>{products.filter(p=>p.category_id===c.id).length} products</small></button>)}</div><select className="mobileCategorySelect" value={active} onChange={e=>setActive(e.target.value)}>{filteredCategories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></aside><section className="stockProducts"><div className="tableTitle"><div><h2>{activeCategory?.name || 'Products'}</h2><p>{activeCategory?.description || 'Selected category products'}</p></div></div><div className="tableWrap"><table><thead><tr><th>Name</th><th>Description</th><th>Barcode</th><th>Price</th><th>Quantity</th><th></th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.description}</td><td>{p.barcode}</td><td>{money(p.price)}</td><td>{p.quantity}</td><td><button className="ghost" onClick={()=>{setEdit(p);setModal('product');}}>Edit</button></td></tr>)}</tbody></table></div></section></div>{modal==='category'&&<Modal title="Create Category" onClose={()=>setModal(null)}><form onSubmit={saveCategory} className="form"><input name="name" required placeholder="Name"/><textarea name="description" placeholder="Description"/><button className="primary">Save Category</button></form></Modal>}{modal==='product'&&<Modal title={edit?'Edit Product':'Add Product'} onClose={()=>{setModal(null);setEdit(null);}}><form onSubmit={saveProduct} className="form"><input name="name" defaultValue={edit?.name} required={!edit} placeholder="Name"/><textarea name="description" defaultValue={edit?.description} placeholder="Description"/><input name="barcode" autoFocus defaultValue={edit?.barcode} placeholder="Barcode - scan or type"/><input name="price" type="number" step="0.01" defaultValue={edit?.price} required={!edit} placeholder="Price"/><input name="quantity" type="number" defaultValue={edit?.quantity} required={!edit} placeholder="Quantity"/><button className="primary">Save Product</button></form></Modal>}</div>;
}
